### ISSUE TITLE
Windows 10 Standby/Resume - abas-watchdog has stopped working

### ISSUE THREAD

**Issue by mrasp** [mrothenbuecher/abas-watchdog#1]
Wenn Windows 10 Rechner nicht heruntergefahren, sondern in den Standby versetzt und wieder aufgeweckt werden, dann stürzt der abas-watchdog nach dem Starten (Anmeldung abas-ERP) mit der Fehlermeldung "abas-watchdog has stopped working" ab.

![image](https://user-images.githubusercontent.com/11809913/37020421-fe7eda40-211b-11e8-8d10-ff5d39e9b669.png)

**Comment by mrothenbuecher** [comment]
Scheint in der aktuellsten Version behoben zu sein. Ich kann es im [aktuellen Release](https://github.com/mrothenbuecher/abas-watchdog/releases/tag/0.5.5) nicht mehr nachvollziehen.
